### ISSUE TITLE
idtoken 

### ISSUE THREAD

**Issue by kilik128** [tungdo0602/Dream.ai-Art-Generator#1]
Traceback (most recent call last):
  File "C:\package\Dream.ai-Art-Generator-main\Dream.ai-Art-Generator-main\main.py", line 188, in <module>
    go()
  File "C:\package\Dream.ai-Art-Generator-main\Dream.ai-Art-Generator-main\main.py", line 155, in go
    token = createToken()['idToken']
KeyError: 'idToken'

**Comment by tungdo0602** [comment]
I think bc it can't fetch the data to get the idToken value
